### ISSUE TITLE
Add responsive design

### ISSUE THREAD

**Issue by evertcode** [evertcode/hacktoberfest-issues-hunt-search#1]
[ ] Responsive design.

![Screenshot_20211015-203839_Chrome](https://user-images.githubusercontent.com/3246481/137568658-c3716406-3ed4-4690-9024-191e8895cd6c.jpg)

**Comment by ArnavPuri** [comment]
OK, I will get started on this. I see the link column is not there anymore so it makes things a bit easier 😅
Just to fly this by, this issue doesn't have the `hacktoberfest` tag, while the other issue has, is it by mistake or do you not want to include this in Hacktoberfest?

**Comment by evertcode** [comment]
Sorry, it was a mistake, I already added the `hacktoberfest` tag to the issue.
