### ISSUE TITLE
500 Internal Server Error

### ISSUE THREAD

**Issue by vinitshahdeo** [evertcode/hacktoberfest-issues-hunt-search#9]
The [URL](https://hacktoberfest-issues.vercel.app/) is returning `500 Internal Server Error`. Can you please look into this?

![Screenshot 2021-12-05 at 4 24 16 PM](https://user-images.githubusercontent.com/20594326/144743644-91535a0e-7c70-44c9-b3db-ae303fc11634.png)

**Comment by evertcode** [comment]
Thank you for reporting the error, at this moment the problem has been solved.
